name: PR Integration to Main

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'integration'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: integration

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create credentials.yaml from secret
        run: |
          echo "${{ secrets.CREDENTIALS_YAML }}" > test_credentials/credentials.yaml

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and capture output
        id: run-tests
        run: |
          python test_script.py > output.log
          cat output.log

      - name: Post test results as a comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('output.log', 'utf8');
            const truncatedOutput = output.length > 60536 ? '... [truncated]\n' + output.slice(-60536) : output;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Test Script Output\n\`\`\`\n${output}\n\`\`\``
            });
